PREFIX asio:         <http://purl.org/hercules/asio/core#>
PREFIX asioModules:  <http://purl.org/hercules/asio/modules#>
PREFIX atold:   <http://publications.europa.eu/resource/authority/>
PREFIX foaf:    <https://xmlns.com/foaf/0.1/>
PREFIX geonames: <http://purl.org/roh/mirror/geonames#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX vivo:    <http://purl.org/roh/mirror/vivo>
PREFIX obo:     <http://purl.org/roh/mirror/obo/ro#>

CONSTRUCT {
    ?x a skos:Concept .
} WHERE {
    ?x a skos:Concept .
    ?x asio:hasCode ?someCode
    {
      ?x skos:inScheme asioModules:CountryClassification
    } UNION {
      ?x skos:inScheme atold:country
    } UNION {
      ?x skos:exactMatch ?y .
      ?y skos:inScheme asioModules:CountryClassification 
    } UNION {
      ?x skos:closeMatch ?y .
      ?y skos:inScheme asioModules:CountryClassification
    } UNION {
      ?x skos:exactMatch ?y .
      ?y skos:inScheme atold:country .
    } UNION {
      ?x skos:closeMatch ?y .
      ?y skos:inScheme atold:country .
    }
}

