prefix roh: <http://purl.org/roh_edma#>
prefix ro:  <http://purl.org/roh_edma/mirror/obo/ro#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix uneskos:  <http://purl.org/roh/unesco-individuals#>
prefix vivo: <http://purl.org/roh_edma/mirror/vivo#> 


SELECT  ?centro ?centerName  ?universityName 
 WHERE { 
      ?centro a ?centroClass;
                 roh:hasKnowledgeArea uneskos:120304.
  OPTIONAL{?universidad_uri a vivo:University;
                    ro:BFO_0000051+ ?centro;
					roh:title  ?universityName.}
  OPTIONAL {?centro roh:title ?centerName.}
  FILTER(?centroClass = roh:ResearchGroup || ?centroClass = roh:ResearchInstitute). 
  }