prefix vivo: <http://w3id.org/roh/mirror/vivo#>
prefix roh: <http://w3id.org/roh#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?centre (COUNT(?seal) AS ?numberOfSeals) WHERE {
  ?centre a ?centerClass ; # get entities of type ResearchInstitute
          roh:hasAccreditation  ?seal . # with property hasSealOfQuality
  ?seal a roh:SealOfQuality.
  Filter(?centerClass = roh:ResearchInstitute || ?centerClass = roh:ResearchGroup)
}
GROUP BY ?centre
ORDER BY DESC(?numberOfSeals)
LIMIT 10