# En esta consulta hay que comprobar que funciona la parte de consultar a Geonames, ya que en Fuseki no funcionan las querys federadas

prefix vivo: <http://purl.org/roh_edma/mirror/vivo#>
prefix roh: <http://purl.org/roh_edma#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix foaf: <http://purl.org/roh_edma/mirror/foaf#>
prefix ro: <http://purl.org/roh_edma/mirror/obo/ro#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ero: <http://purl.org/roh_edma/mirror/obo/ero#>
prefix gn: <http://purl.org/roh_edma/mirror/geonames#>
prefix iao: <http://purl.org/roh_edma/mirror/obo/iao#>
prefix dc: <http://purl.org/dc/elements/1.1/>

SELECT
(COUNT(DISTINCT ?publication) as ?publicationCount) ?comunidadAutonoma
WHERE {
  ?publication         a bibo:Document ;
                       vivo:hasPublicationVenue        ?journal;
                       roh:correspondingOrganization ?organization.
  ?journal	a bibo:Journal        .
  ?organization	gn:locatedIn        ?location .
 #SERVICE ?location {
 # 	?location <http://www.geonames.org/ontology#parentADM1> ?comunidadAutonoma .
#  }
}
GROUP BY ?comunidadAutonoma