prefix vivo: <http://purl.org/roh_edma/mirror/vivo#>
prefix roh: <http://purl.org/roh_edma#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?patent ?centre ?knowledgeArea 
WHERE {
  ?patent a bibo:Patent ;
          roh:correspondingOrganization ?centre;
          roh:hasKnowledgeArea ?knowledgeArea .
  ?centre a ?classCenter.
  Filter(?classCenter = roh:ResearchGroup || ?classCenter =roh:ResearchInstitute)
  
} GROUP BY ?patent ?centre ?knowledgeArea 