PREFIX vivo: <https://w3id.org/roh/mirror/vivo#>
PREFIX roh: <https://w3id.org/roh#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <https://w3id.org/roh/mirror/foaf#>
PREFIX bfo: <https://w3id.org/roh/mirror/obo/bfo#>

SELECT DISTINCT ?project ?centre ?knowledgeArea
WHERE {
	?project	a vivo:Project ;
				roh:hasKnowledgeArea ?knowledgeArea ;
				vivo:relates ?role ;
				vivo:dateTimeInterval ?dateTimeInterval .
	?role	a ?roleClass ;
			roh:roleOf ?centre .
	?roleClass rdfs:subClassOf* bfo:BFO_0000023 .
	?centre a ?organization .
	?dateTimeInterval	vivo:start ?startDateTimeValue ;
						vivo:end ?endDateTimeValue . 
	?startDateTimeValue vivo:dateTime ?start . 
	?endDateTimeValue vivo:dateTime ?end . 
  	FILTER (YEAR(?start) >= "2010"^^xsd:integer && YEAR(?end) <= "2020"^^xsd:integer )
}