PREFIX roh: <http://w3id.org/roh#>
prefix vivo:  <http://w3id.org/roh/mirror/vivo#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://w3id.org/roh/mirror/foaf#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix uneskos-individuals:  <http://w3id.org/roh/unesco-individuals#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?RO ?researchObjectClass ?dateTimeValue 
WHERE{
?RO a roh:ResearchObject;
      a  ?researchObjectClass;
      roh:hasKnowledgeArea uneskos-individuals:120304;
      roh:seqOfAuthors+|bibo:authorList ?authorList;
      vivo:dateTimeValue ?date  .
?date  vivo:dateTime ?dateTimeValue .
?authorList a rdf:Seq;
            rdfs:member ?author .
?author roh:hasPosition ?position .
?position vivo:relates ?center .
?center a ?centerClass. 
Filter(?centerClass = roh:ResearchGroup || ?centerClass = roh:ResearchInstitute).
FILTER NOT EXISTS {
    ?RO a ?otherClass .
    ?otherClass rdfs:subClassOf ?researchObjectClass .
    FILTER (?otherClass != ?researchObjectClass)
}
FILTER (str(?researchObjectClass) != "http://w3id.org/roh#ResearchObject")
}
 ORDER BY ASC(?dateTimeValue )
