PREFIX roh: <http://purl.org/roh#>
prefix vivo:  <http://purl.org/roh/mirror/vivo#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://purl.org/roh/mirror/foaf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>


SELECT ?invention ?dateTimeValue  WHERE {
 
    ?invention roh:produces ?researchObject ;
           a ?tipo .
 
   ?researchObject vivo:dateTimeValue ?date  .
   ?date  vivo:dateTime ?dateTimeValue .


   FILTER NOT EXISTS{
       values ?avoid { roh:DegreeSupervisingRelationship roh:MasterSupervisingRelationship roh:PhDSupervisingRelationship roh:SupervisingRelationship }
       ?invention a ?avoid .
   } 
  
}
ORDER BY ASC(?dateTimeValue ) LIMIT 1