PREFIX roh: <http://purl.org/roh#>
prefix vivo:  <http://purl.org/roh/mirror/vivo#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://purl.org/roh/mirror/foaf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>


SELECT ?dosier WHERE {
 
    ?dosier vivo:relates ?project .
    ?project rdfs:label ?projectLabel .
   FILTER(?projectLabel = "sample-Project-3826")      

}
