PREFIX roh: <http://w3id.org/roh#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
PREFIX uneskos-individuals: <http://w3id.org/roh/unesco-individuals#>
PREFIX skos1: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?project 
WHERE {
{
?project a vivo:Project ;
            roh:hasKnowledgeArea ?knowledgeArea .
?knowledgeArea skos1:broader+|skos1:narrower+|skos1:related+ uneskos-individuals:1203 .
} #UNION {
#uneskos-individuals:1203 skos1:broader+ ?topKnowledgeArea .
#        ?topKnowledgeArea skos1:narrower+ ?otherKnowledgeArea .
#?project roh:hasKnowledgeArea ?otherKnowledgeArea ;
#        a vivo:Project .
#}
}
