PREFIX roh: <https://w3id.org/roh#>
prefix vivo:  <https://w3id.org/roh/mirror/vivo#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <https://w3id.org/roh/mirror/foaf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?project ?KnowledgeArea WHERE {
  ?project a  vivo:Project;
          roh:hasKnowledgeArea ?KnowledgeArea . 
  ?KnowledgeArea  a roh:UNESCOKnowledgeArea .

}
ORDER BY DESC(?project )