PREFIX roh: <http://w3id.org/roh#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
PREFIX uneskos: <http://w3id.org/roh/unesco-individuals#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?project 
WHERE 
{
?project a vivo:Project ;
            roh:hasKnowledgeArea ?knowledgeArea .
?knowledgeArea skos:broader+|skos:narrower+|skos:related+ uneskos:1203 .
} UNION {
uneskos:1203 skos:broader+ ?topKnowledgeArea .
        ?topKnowledgeArea skos:narrower+ ?otherKnowledgeArea .
?project roh:hasKnowledgeArea ?otherKnowledgeArea ;
        a vivo:Project .
}
}
