PREFIX roh: <http://purl.org/roh_edma#>
PREFIX vivo: <http://purl.org/roh_edma/mirror/vivo#>
PREFIX foaf: <http://purl.org/roh_edma/mirror/foaf#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bibo: <http://purl.org/roh_edma/mirror/bibo#>
prefix ro: <http://purl.org/roh_edma/mirror/obo/ro#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix bfo: <http://purl.org/roh_edma/mirror/obo/bfo#> 
SELECT DISTINCT  ?researcher ?organization  ?proyect 
WHERE {
 ?researcher  a foaf:Person.
  ?proyect a vivo:Project;
           vivo:relates ?role;
           vivo:dateTimeInterval ?datetimeInterval.
  ?datetimeInterval vivo:start ?startTimeValue;
                    vivo:end ?endTimeValue.
  ?startTimeValue vivo:dateTime ?start .
  ?endTimeValue vivo:dateTime ?end.

  ?role ro:RO_0000052 ?researcher;
         roh:roleOf ?organization.
  ?organization a ?researchGroupClass. 
  Filter( ?researchGroupClass = roh:ResearchGroup || ?researchGroupClass = roh:ResearchInstitute)
  FILTER (YEAR(?start) >= "2015"^^xsd:integer && YEAR(?end) <= "2022"^^xsd:integer )
}
