PREFIX roh: <http://purl.org/roh#>
PREFIX vivo: <http://purl.org/roh/mirror/vivo#>
PREFIX foaf: <http://purl.org/roh/mirror/foaf#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?researcher ?project ?organization ?start ?end
WHERE {
  	?project	a vivo:Project ;
  				vivo:relates ?role ;
  				vivo:dateTimeInterval ?dateTimeInterval .
	?dateTimeInterval	vivo:end ?endDateTimeValue ;
						vivo:start ?startDateTimeValue .
	?endDateTimeValue vivo:dateTime ?end .
	?startDateTimeValue vivo:dateTime ?start .
	?role roh:roleOf ?researcher .
	?researcher roh:hasPosition ?position .
  	?position vivo:relates ?organization .
	FILTER (YEAR(?start) <= "2020"^^xsd:integer && YEAR(?end) >= "2010"^^xsd:integer )
}