PREFIX roh: <https://w3id.org/roh#>
PREFIX vivo: <https://w3id.org/roh/mirror/vivo#>
PREFIX foaf: <https://w3id.org/roh/mirror/foaf#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bibo: <https://w3id.org/roh/mirror/bibo#>

SELECT DISTINCT ?researcher ?researchObject ?organization 
WHERE {
	?researchObject a roh:ResearchObject ;
	bibo:authorList ?authorList ;
	vivo:dateIssued ?dateTimeValue .
	?dateTimeValue vivo:dateTime ?date .
	?authorList rdfs:member ?researcher .
	?researcher roh:hasPosition ?position .
	?position vivo:relates ?organization .
  	FILTER (YEAR(?date) >= "2000"^^xsd:integer && YEAR(?date) <= "2010"^^xsd:integer )
}
ORDER BY ?researcher