prefix ro: <http://w3id.org/roh/mirror/obo/ro#> 
prefix vivo: <http://w3id.org/roh/mirror/vivo#> 
prefix roh: <http://w3id.org/roh#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#> 
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://w3id.org/roh/mirror/foaf#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix uneskos:  <http://w3id.org/roh/unesco-individuals#>

SELECT distinct ?organization ?researchObject  ?researchObjectClass   ?title ?repository ?keyword ?doi ?project
WHERE {
  
  ?researchObject a roh:ResearchObject;
        roh:correspondingOrganization ?organization;
        a ?researchObjectClass;
        roh:hasKnowledgeArea uneskos:120304. 

  ?organization a ?classOrganization. 
  ?researchObject  roh:seqOfAuthors+|bibo:authorList ?list.
  ?list a rdf:Seq;
          rdfs:member <http://w3id.org/roh/data#investigador-2>.
  ?researchObject roh:producedBy ?project.
  ?project  a vivo:Project.
  Optional{?researchObject roh:title ?title}   
  Optional{ ?researchObject vivo:doi ?doi. }
  Optional{?researchObject roh:partOfRepository ?repository.}
  Optional {?researchObject vivo:freetextKeyword ?keyword}
  Filter(?classOrganization = roh:ResearchInstitute || ?classOrganization = roh:ResearchGroup)
  FILTER NOT EXISTS {
            ?researchObject a ?otherClass .
            ?otherClass rdfs:subClassOf ?researchObjectClass .
        FILTER (?otherClass != ?researchObjectClass)
  }
FILTER (str(?researchObjectClass) != "http://w3id.org/roh#ResearchObject")
} 
GROUP BY ?organization ?researchObject  ?researchObjectClass ?author ?dateTime ?title ?repository ?keyword ?doi ?project


