prefix vivo: <http://purl.org/roh_edma/mirror/vivo#>
prefix roh: <http://purl.org/roh_edma#>
prefix obo: <http://purl.obolibrary.org/obo/>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix foaf: <http://purl.org/roh_edma/mirror/foaf#>
prefix unesco: <http://purl.org/roh/unesco-individuals#>
prefix ro: <http://purl.org/roh_edma/mirror/obo/ro#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ero: <http://purl.org/roh_edma/mirror/obo/ero#>
prefix gn: <http://purl.org/roh_edma/mirror/geonames#>
prefix iao: <http://purl.org/roh_edma/mirror/obo/iao#>
prefix dc: <http://purl.org/dc/elements/1.1/>

SELECT  ?publication ?date ?impactFacor ?quartile ?organization ?journal   ?author
WHERE {
  ?publication  a bibo:Document ;
                vivo:hasPublicationVenue        ?journal;
                roh:correspondingOrganization ?organization;
					      roh:correspondingAuthor ?author;
					      vivo:dateIssued ?dateTime;
					      roh:hasMetric ?metric.
	?metric a roh:PublicationMetric;
			      roh:impactFactor ?impactFacor;
            roh:quartile ?quartile.
	?dateTime a vivo:DateTimeValue ;
            vivo:dateTime ?date.
	?author a foaf:Person.
  ?journal	a bibo:Journal   .

  } 
  Order By ?publication DESC(?date) ?impactFacor ?quartile  ?journal
