prefix vivo: <http://w3id.org/roh/mirror/vivo#>
prefix roh: <http://w3id.org/roh#>
prefix obo: <http://purl.obolibrary.org/obo/>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix foaf: <http://w3id.org/roh/mirror/foaf#>
prefix unesco: <http://w3id.org/roh/unesco-individuals#>
prefix ro: <http://w3id.org/roh/mirror/obo/ro#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ero: <http://w3id.org/roh/mirror/obo/ero#>
prefix gn: <http://w3id.org/roh/mirror/geonames#>
prefix iao: <http://w3id.org/roh/mirror/obo/iao#>
prefix dc: <http://purl.org/dc/elements/1.1/>
 
SELECT distinct ?publication ?citationCount ?nameOfMetric ?dateMetricPublication ?journal ?impactFactorName ?impactFacor ?quartile ?organization ?author
WHERE {
  ?publication  a bibo:Document ;
                vivo:hasPublicationVenue        ?journal;
                roh:correspondingOrganization ?organization; 
					      roh:correspondingAuthor ?author;
					      vivo:dateIssued+|vivo:dateTimeValue ?dateTime;
					      roh:hasMetric ?metric.

	?metric a roh:PublicationMetric;
			      roh:citationCount ?citationCount;
         		roh:metricName ?nameOfMetric;
          	vivo:dateTimeValue+|vivo:dateIssued ?DateMetricPublication.
  
?DateMetricPublication a vivo:DateTimeValue ;
                     vivo:dateTime ?dateMetricPublication. 
 
	?dateTime a vivo:DateTimeValue ;
            vivo:dateTime ?date.
  
	?author a foaf:Person.
  
  ?journal	a bibo:Journal;
            roh:hasMetric ?metricJournal.
  
  ?metricJournal a roh:JournalMetric;
              roh:impactFactor ?impactFacor;
            	roh:quartile ?quartile;
              roh:impactFactorName ?impactFactorName;
              vivo:dateTimeValue+|vivo:dateIssued ?DateMetricJournal.
?DateMetricJournal a vivo:DateTimeValue ;
              vivo:dateTime ?dateMetricJournal. 

Filter(year(?dateMetricJournal) = year(?date))
  } 
 
