PREFIX roh: <http://purl.org/roh_edma#>
PREFIX uneskos: <http://purl.org/roh/unesco-individuals#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#>
prefix ro:  <http://purl.org/roh_edma/mirror/obo/ro#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix bfo: <http://purl.org/roh_edma/mirror/obo/bfo#>
PREFIX uneskos: <http://purl.org/roh/unesco-individuals#>
prefix foaf: <http://purl.org/roh_edma/mirror/foaf#>
prefix uneskos:  <http://purl.org/roh/unesco-individuals#>
prefix vivo: <http://purl.org/roh_edma/mirror/vivo#> 

SELECT ( year(?dateStartProject) as ?year) 
  (count( distinct?project) As ?CountProject) (count( distinct ?person) as ?researchers )  (?CountProject / ?researchers  AS ?rate) ?knowledgeArea 
where{

    ?project a vivo:Project;
            vivo:dateTimeInterval ?dateTimeIntervalProject;
            roh:hasKnowledgeArea ?knowledgeArea;
          vivo:relates  ?rol.
    
    ?dateTimeIntervalProject  vivo:start ?startProject.
    ?startProject  vivo:dateTime ?dateStartProject.

    ?rol a ?rolClass; 
        roh:roleOf   <http://purl.org/roh_edma/data#grupo-investigacion-1>.

    ?rolClass rdfs:subClassOf bfo:BFO_0000023.

    ?person roh:hasPosition ?position;
            a foaf:Person.
    
    ?position vivo:dateTimeInterval ?dateTimeInterval;
                vivo:relates <http://purl.org/roh_edma/data#grupo-investigacion-1>;
              a roh:ResearcherPosition.
    
    ?dateTimeInterval vivo:start ?satarNode.
    ?satarNode vivo:dateTime  ?star.

Filter(year(?star) <= year(?dateStartProject)  )
filter not exists{
    ?dateTimeIntervalProject  
    vivo:end ?endProject.
   ?endProject vivo:dateTime ?dateEndProject. 
    ?dateTimeInterval vivo:end ?endNode.
                ?endNode vivo:dateTime  ?end.
    Filter( year(?end) > year(?dateEndProject) )
}
}
Group by  ?dateStartProject  ?knowledgeArea ?CountPublication ?rate 
order by ?year