PREFIX roh: <http://w3id.org/roh#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#> 

SELECT distinct ?document WHERE 

    
  {   ?document roh:correspondingAuthor <http://w3id.org/roh/data#investigador-1>.

        ?document  roh:seqOfAuthors+| bibo:authorList ?authorList.
        ?authorList
                rdfs:member 	<http://w3id.org/roh/data#investigador-1>.
  
}