PREFIX roh: <http://purl.org/roh_edma#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#> 

SELECT distinct ?document WHERE {
  {
  ?document roh:correspondingAuthor <http://purl.org/roh_edma/data#investigador-1>.
    } 
  union
  { ?document  roh:seqOfAuthors ?authorList.
    ?authorList a rdf:Seq;
                rdfs:member 	<http://purl.org/roh_edma/data#investigador-1>.
  
  }union
  { ?document  bibo:authorList ?authorList.
    ?authorList a rdf:Seq;
                rdfs:member 	<http://purl.org/roh_edma/data#investigador-1>.
  
  }
}