PREFIX roh: <http://w3id.org/roh#>
PREFIX ro: <http://purl.org/obo/owl/ro#>
prefix foaf: <http://w3id.org/roh/mirror/foaf#>
prefix vivo: <http://w3id.org/roh/mirror/vivo#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?founder ?company 
where{

    ?founder a foaf:Person;
             roh:companyFounder ?company.
    ?company a vivo:Company;
              roh:isStartup "true"^^xsd:boolean. 
}