PREFIX roh: <https://w3id.org/roh#>
prefix vivo:  <https://w3id.org/roh/mirror/vivo#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <https://w3id.org/roh/mirror/foaf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# No results but not because of the query itself but because of the validation data
SELECT DISTINCT  ?person ?publicacion  ?metric ?numCitations  WHERE {

     ?publicacion vivo:publisher ?org .
     ?publicacion roh:isCoauthoredBy|roh:correspondingAuthor ?person .
     ?person a foaf:Person .
  
      ?publicacion roh:hasMetric ?metric .
      ?metric roh:citationCount ?numCitations .
    
  
}