PREFIX roh: <http://w3id.org/roh#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
PREFIX foaf: <http://w3id.org/roh/mirror/foaf#>
prefix ro: <http://w3id.org/roh/mirror/obo/ro#>
SELECT DISTINCT ?project ?organization ?otherOrganization 
WHERE {
?project a vivo:Project ;
		vivo:relates ?role ;
		vivo:relates ?otherRole .
?role roh:roleOf ?organization .
?organization a foaf:Organization .
?otherRole roh:roleOf ?otherOrganization .
?otherOrganization a foaf:Organization .
FILTER (?organization != ?otherOrganization) 
}