PREFIX roh: <https://w3id.org/roh#>
prefix vivo:  <https://w3id.org/roh/mirror/vivo#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <https://w3id.org/roh/mirror/foaf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>


SELECT (SUM(?fundingAmount) as ?fundingSum) ?orgLabel ?knowledgeLabel WHERE {

   ?person  a   foaf:Person .
   ?person roh:hasPosition ?position .
   ?position vivo:relates ?org .

  ?funding roh:grants ?org ;
           roh:monetaryAmount ?fundingAmount .

 ?org  roh:hasKnowledgeArea ?knowledgeArea ;
        rdfs:label ?orgLabel .

   ?knowledgeArea rdfs:label ?knowledgeLabel .    
} GROUP BY ?orgLabel ?knowledgeLabel