PREFIX roh: <https://w3id.org/roh#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?centre (COUNT(?seal) AS ?numberOfSeals) WHERE {
  ?centre a roh:ResearchInstitute ; # get entities of type ResearchInstitute
          roh:hasSealOfQuality ?seal . # with property hasSealOfQuality
}
GROUP BY ?centre
ORDER BY DESC(?numberOfSeals)
LIMIT 10