PREFIX roh: <http://w3id.org/roh#>
PREFIX uneskos-individuals: <http://w3id.org/roh/unesco-individuals#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix ro:  <http://w3id.org/roh/mirror/obo/ro#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix bfo: <http://w3id.org/roh/mirror/obo/bfo#>
PREFIX uneskos-individuals: <http://w3id.org/roh/unesco-individuals#>
prefix foaf: <http://w3id.org/roh/mirror/foaf#>
prefix uneskos-individuals:  <http://w3id.org/roh/unesco-individuals#>
prefix vivo: <http://w3id.org/roh/mirror/vivo#> 

SELECT ( year(?dateStartProject) as ?year) ?knowledgeArea
  (count( distinct?project) As ?CountProject)   ?classClasificacionProject
where{

    ?project a vivo:Project;
            vivo:dateTimeInterval ?dateTimeIntervalProject;
            roh:hasKnowledgeArea ?knowledgeArea.
          
    
    ?dateTimeIntervalProject  vivo:start ?startProject.
    ?startProject  vivo:dateTime ?dateStartProject.
    Optional{?project
    roh:hasProjectCategorization  ?projectClasificacion.
    ?projectClasificacion a ?classClasificacionProject.
    FILTER NOT EXISTS { 
        ?projectClasificacion a ?otherClass.
        ?otherClass rdfs:subClassOf ?classClasificacionProject .
        FILTER (?otherClass != ?classClasificacionProject) } 
        }             
}
Group by  ?dateStartProject  ?knowledgeArea ?classClasificacionProject
order by ?year