PREFIX roh: <http://purl.org/roh#>
PREFIX vivo: <http://purl.org/roh/mirror/vivo#>
PREFIX foaf: <http://purl.org/roh/mirror/foaf#>

SELECT ?researcher ?grant 
WHERE {
    ?contract a roh:PersonContract  .
    ?researcher roh:hasContract ?contract ;
    a foaf:Person

    {
        SELECT ?grant 
        WHERE {
            ?grant a roh:Grant ;
            roh:hasContract ?contract .
        }
    }
}