PREFIX roh: <https://w3id.org/roh#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# hasSealOfQuality domain should be SealOfQuality and not ResearchInstitute as featuring in the roh-core
SELECT ?centre ?sealLabel WHERE {
  ?centre a roh:ResearchInstitute ;
          roh:hasSealOfQuality ?seal . # with property hasSealOfQuality
  ?seal rdfs:label ?sealLabel
          
  FILTER( ?sealLabel = "sample-ResearchInstitute-2941")
}
