PREFIX roh: <http://purl.org/roh#>
PREFIX vivo: <http://purl.org/roh/mirror/vivo#>
PREFIX ro: <http://purl.org/roh/mirror/obo/ro#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?project ?fundingProgram ?otherOrganization ?university
WHERE{
    ?project	a vivo:Project ;
    			vivo:dateTimeInterval ?dateTimeInterval ;
    			vivo:relates ?role ;
    			vivo:relates ?otherRole ;
    			roh:isSupportedBy ?funding .
    ?funding roh:fundedBy ?fundingProgram .
    ?role roh:roleOf ?researchOrganization .
    ?otherRole roh:roleOf ?otherOrganization .
    ?university ro:BFO_0000051 ?otherOrganization .
    # ?university a vivo:University .
    ?dateTimeInterval	vivo:start ?start ;
    					vivo:end ?end .
    ?start vivo:dateTime ?startTime .
    ?end vivo:dateTime ?endTime .
  	FILTER (?otherOrganization != ?university)
  	FILTER (YEAR(?startTime) <= "2020"^^xsd:integer && YEAR(?endTime) >= "2010"^^xsd:integer)
}