PREFIX roh: <http://w3id.org/roh#>
PREFIX foaf: <http://w3id.org/roh/mirror/foaf#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix vivo: <http://w3id.org/roh/mirror/vivo#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix ro: <http://w3id.org/roh/mirror/obo/ro#> 
prefix foaf: <http://w3id.org/roh/mirror/foaf#>

SELECT distinct ?gender (COUNT( distinct ?journal_article) as ?count)  
 WHERE {
?journal_article a bibo:Document ;
        vivo:dateIssued+|vivo:dateTimeValue ?dateTimeValue ;
                 vivo:hasPublicationVenue        ?journal.
  
?dateTimeValue vivo:dateTime ?date .
?authorList rdfs:member ?researcher . 
?researcher foaf:gender ?gender .
?journal a bibo:Journal;
                roh:hasMetric ?jorunalMetric.

?jorunalMetric a roh:JournalMetric;
    roh:impactFactor ?impactFactor;
     vivo:dateTimeValue+|vivo:dateIssued ?DateMetricJournal.
?DateMetricJournal a vivo:DateTimeValue ;
              vivo:dateTime ?dateMetricJournal. 

Filter(year(?dateMetricJournal) = year(?date))
} GROUP BY ?gender 