PREFIX roh: <http://purl.org/roh_edma#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix vivo: <http://purl.org/roh_edma/mirror/vivo#> 
prefix bfo: <http://purl.org/roh_edma/mirror/obo/bfo#>

select  distinct ?project 
where{

?project a vivo:Project.
Filter not exists{
            ?project  vivo:relates ?rol.
            ?rol a ?rolClass; 
                roh:roleOf  <http://purl.org/roh_edma/data#grupo-investigacion-1>.
            ?rolClass rdfs:subClassOf* bfo:BFO_0000023.
            }
}