PREFIX roh: <http://w3id.org/roh#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix vivo: <http://w3id.org/roh/mirror/vivo#> 
prefix bfo: <http://w3id.org/roh/mirror/obo/bfo#>

select  distinct ?project 
where{

?project a vivo:Project.
Filter not exists{
            ?project  vivo:relates ?rol.
            ?rol a ?rolClass; 
                roh:roleOf  <http://w3id.org/roh/data#grupo-investigacion-1>.
            ?rolClass rdfs:subClassOf* bfo:BFO_0000023.
            }
}