PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#> 
prefix foaf: <http://w3id.org/roh/mirror/foaf#>
prefix roh: <http://w3id.org/roh#>
prefix vivo:  <http://w3id.org/roh/mirror/vivo#>
prefix uneskos-individuals: <http://w3id.org/roh/unesco-individuals#>
prefix ro: <http://w3id.org/roh/mirror/obo/ro#> 
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
SELECT   distinct ?center (year( ?dateeMetricJournal) as ?year)  (SUM( distinct ?citas) AS ?CountCitas)  

WHERE {

?publication a bibo:Document;
             roh:correspondingOrganization ?center;
              roh:hasMetric ?metric;
              vivo:dateTimeValue+|vivo:dateIssued ?DateMetricJournal.
?DateMetricJournal a vivo:DateTimeValue ;
              vivo:dateTime ?dateeMetricJournal. 
?metric a roh:PublicationMetric ;
         roh:metricName "Web of Science"^^xsd:string;
        roh:citationCount ?citas.
         

?center a ?centerClass.
Filter(?centerClass = roh:ResearchGroup || ?centerClass=roh:ResearchInstitute)
}Group by ?dateeMetricJournal ?center 

