PREFIX roh: <https://w3id.org/roh#>
PREFIX foaf: <https://w3id.org/roh/mirror/foaf#>
PREFIX vivo: <https://w3id.org/roh/mirror/vivo#>
SELECT ?researchGroup ?citations
WHERE {
?researcher a foaf:Person ;
  roh:hasPosition ?position .
  
?metric roh:metricOf ?researcher ;
        roh:citationCount ?citations .
?position vivo:relates ?researchGroup .
?researchGroup a roh:ResearchGroup .
} GROUP BY ?researchGroup ?citations
