PREFIX roh: <https://w3id.org/roh#>
PREFIX vivo: <https://w3id.org/roh/mirror/vivo#>
PREFIX bibo:  <https://w3id.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?researchGroup ?journalArticle
WHERE {
?researcher roh:hasPosition ?position .
?position vivo:relates ?researchGroup .
?researchGroup a roh:ResearchGroup .
?journalArticle bibo:authorList ?authorList ;
vivo:hasPublicationVenue <http://example.org/individual/sample-Periodical-1635> .
?authorList rdfs:member ?researcher .
}
