PREFIX roh: <http://w3id.org/roh#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
PREFIX bibo:  <http://w3id.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix iao: <http://w3id.org/roh/mirror/obo/iao#>
SELECT DISTINCT ?researcher ?center ?journalArticle 
WHERE {
?journalArticle a                        bibo:AcademicArticle;
        bibo:authorList+| roh:seqOfAuthors ?authorList ;
        roh:correspondingOrganization ?center;
        vivo:hasPublicationVenue <http://w3id.org/roh/data#excelent-journal> .
?authorList rdfs:member ?researcher .
?center a ?classCenter. 
Filter(?classCenter = roh:ResearchGroup || ?classCenter = roh:ResearchInstitute)
}
