PREFIX roh: <http://purl.org/roh_edma#>
PREFIX vivo: <http://purl.org/roh_edma/mirror/vivo#>
PREFIX bibo:  <http://purl.org/roh_edma/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?publication 
WHERE {
?publication 
                               roh:title ?title ;
                               a bibo:Article ;
                               roh:correspondingOrganization <http://purl.org/roh_edma/data#grupo-investigacion-1>.
FILTER regex(?title, "great", "i")}