PREFIX roh: <http://w3id.org/roh#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
PREFIX bibo:  <http://w3id.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?journal ?knowledgeArea ?nameOfMetric
WHERE {
?journalArticle vivo:hasPublicationVenue ?journal ;
				roh:hasKnowledgeArea ?knowledgeArea ;
				roh:correspondingOrganization <http://w3id.org/roh/data#grupo-investigacion-1> .
?journal a bibo:Journal;
roh:hasMetric ?metric.
?metric roh:quartile "Q2".
Optional{?metric roh:impactFactorName ?nameOfMetric}
}
