PREFIX iao: <http://w3id.org/roh/mirror/obo/iao#>
PREFIX roh: <http://w3id.org/roh#>
PREFIX bibo:  <http://w3id.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
SELECT ?researcher ?journal ?impactFactor  WHERE {
?journal a iao:IAO_0000013 ;
        vivo:dateIssued ?dateTimeValue ;
        bibo:authorList+| roh:seqOfAuthors ?authorList ;
        roh:hasMetric ?metric .
?dateTimeValue vivo:dateTime ?date .
?authorList rdfs:member ?researcher . 
?metric roh:impactFactor ?impactFactor;
       roh:metricName "jcr".
FILTER (YEAR(?date) >= "2010"^^xsd:integer && YEAR(?date) <= "2020"^^xsd:integer )
} 
