PREFIX roh: <http://purl.org/roh#>
PREFIX vivo: <http://purl.org/roh/mirror/vivo#>
PREFIX ro: <http://purl.org/roh/mirror/obo/ro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fo: <http://www.w3.org/1999/XSL/Format#>
PREFIX foaf: <http://purl.org/roh/mirror/foaf#>

SELECT ?organization ?project ?company 
WHERE {
	?project	a vivo:Project ;
				vivo:relates ?role ;
				roh:isSupportedBy ?funding ;
  				roh:projectStatus ?projectStatus .
	?funding	ro:BFO_0000051 ?fundingAmount ;
				roh:fundedBy ?fundingProgram .
	?fundingProgram roh:promotedBy ?company .
  	?fundingAmount roh:monetaryAmount ?fundingAmounts .
  	?role roh:roleOf ?organization .
  	?organization a ?researchGroupClass .
  	# ?researchGroupClass	rdfs:subClassOf foaf:Organization .
  	?projectStatus a ?projectStatusClass .
  	FILTER (?projectStatusClass != roh:ProposalSubmitted)
}
