  PREFIX roh: <http://w3id.org/roh#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
PREFIX bibo:  <http://w3id.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX ro: <http://w3id.org/roh/mirror/obo/ro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?university ?Thesis  ?ThesisClass
WHERE {
?Thesis a ?ThesisClass;
          roh:correspondingOrganization ?researchGroup;
			    roh:title ?title .
?researchGroup a roh:ResearchGroup .
?university a vivo:University;
            ro:BFO_0000051+ ?researchGroup .
?ThesisClass rdfs:subClassOf bibo:Thesis.
  
FILTER NOT EXISTS {
    ?Thesis a ?otherClass .
    ?otherClass rdfs:subClassOf ?ThesisClass .
    FILTER (?otherClass != ?ThesisClass)
    }

FILTER (str(?ThesisClass) != "http://w3id.org/roh#ResearchObject")

FILTER regex(?title, "fabulous", "i")}
