PREFIX roh: <http://purl.org/roh#>
prefix vivo:  <http://purl.org/roh/mirror/vivo#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://purl.org/roh/mirror/foaf#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>


SELECT ?document WHERE {
   ?person  a   foaf:Person .
   ?person roh:hasPosition ?position .

   ?position vivo:relates ?org ;
            a vivo:Position .

   ?org  roh:hasKnowledgeArea ?knowledgeArea ;
        rdfs:label ?orgLabel .

   ?knowledgeArea rdfs:label ?knowledgeLabel .
  
  ?document roh:correspondingAuthor ?person .
  

   FILTER(?orgLabel = "sample-AcademicDepartment-6432" && 
         ?knowledgeLabel = "sample-UNESCOKnowledgeArea-5740")      

}