prefix bibo: <http://w3id.org/roh/mirror/bibo#> 
PREFIX roh: <http://w3id.org/roh#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
prefix ero: <http://w3id.org/roh/mirror/obo/ero#>
select ?experimentalProtocol ?repository ?classRepository ?project ?organization 
 ?author   ?ResearchResult
where{
    ?experimentalProtocol  a roh:ExperimentalProtocol.                       
  
 	OPTIONAL{
  			?experimentalProtocol roh:correspondingOrganization ?organization.
  			}
    OPTIONAL{
        ?experimentalProtocol roh:partOfRepository ?repository.
        ?repository a ?classRepository.
     FILTER NOT EXISTS {
	        ?repository 		a ?otherClass .
	        ?otherClass rdfs:subClassOf ?classRepository .
	        FILTER (?otherClass != ?classRepository)
        }
        Filter(str(?classRepository)!="http://www.w3.org/2002/07/owl#NamedIndividual")
        }

    Optional{
        ?experimentalProtocol roh:produces ?experimentalProtocolResult.
        ?experimentalProtocolResult a roh:ExperimentalProtocolResult.
    }
    Optional{
        ?experimentalProtocol roh:seqOfAuthors+|bibo:authorList ?authorList.
        ?authorList rdfs:member ?author. 
    }
    Optional{
        ?experimentalProtocol roh:partOfResearchResult ?ResearchResult.
        ?ResearchResult roh:correspondingAuthor ?author.
    }
   
}