PREFIX roh: <http://w3id.org/roh#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

select ?researchObjectBase ?anotherResearchObject ?classResearchObject
where {
    ?researchObjectBase a roh:ResearchObject;
                    roh:hasSucessor ?anotherResearchObject.
    ?anotherResearchObject a ?classResearchObject.
    FILTER NOT EXISTS {
	        ?researchObjectBase 		a ?otherClass .
	        ?otherClass rdfs:subClassOf ?classResearchObject .
	        FILTER (?otherClass != ?classResearchObject)
        }
    FILTER (str(?classResearchObject) != "http://w3id.org/roh#ResearchObject")
             Filter(str(?classResearchObject)!="http://www.w3.org/2002/07/owl#NamedIndividual")

}