PREFIX roh: <http://w3id.org/roh#>
prefix oa: <http://w3id.org/roh/mirror/oa#>

select ?anotation ?target ?body ?motivation ?author
where{
    ?anotation a oa:Annotation;
                oa:hasTarget ?target;
                oa:hasBody ?body;
                oa:motivatedBy ?motivation;
                roh:correspondingAuthor ?author. 
}
