PREFIX roh: <http://w3id.org/roh#>
prefix oa: <http://w3id.org/roh/mirror/oa#>

select distinct ?target ?anotation  ?body ?annotation2 ?body2
where{
    ?anotation a oa:Annotation;
                oa:hasTarget ?target;
                oa:hasBody ?body.
    ?annotation2 a oa:Annotation;
                oa:hasTarget ?anotation;
                 oa:hasBody ?body2.
}