# En esta consulta hay que comprobar que funciona la parte de consultar a Geonames, ya que en Fuseki no funcionan las querys federadas

PREFIX vivo: <http://purl.org/roh/mirror/vivo#>
PREFIX roh: <http://purl.org/roh#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX bibo: <http://purl.org/roh/mirror/bibo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://purl.org/roh/mirror/foaf#>
PREFIX unesco: <http://purl.org/roh/unesco-individuals#>
PREFIX ro: <http://purl.org/obo/owl/ro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ero: <http://purl.org/roh/mirror/obo/ero#>
PREFIX gn: <http://purl.org/roh/mirror/geonames#>
PREFIX iao: <http://purl.org/roh/mirror/obo/iao#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT
(COUNT(DISTINCT ?publication) as ?publicationCount) ?comunidadAutonoma
WHERE {
  ?publication         a iao:IAO_0000013 ;
                       vivo:hasPublicationVenue        ?journal ;
                       bibo:authorList        ?authorList ;
 				 	   vivo:dateIssued        ?dateTimeValue .
  ?journal	a bibo:Journal        .
  ?authorList	rdfs:member        ?author .
  ?dateTimeValue	vivo:dateTime        ?dateTime .
  ?author	a        foaf:Person .
  ?position roh:positionOf ?author ;
            vivo:relates ?organization .
  ?organization	gn:locatedIn        ?location .
  SERVICE ?location {
  	?location <http://www.geonames.org/ontology#parentADM1> ?comunidadAutonoma .
  }
} 
GROUP BY ?comunidadAutonoma