prefix vivo: <http://purl.org/roh_edma/mirror/vivo#>
prefix roh: <http://purl.org/roh_edma#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#>
prefix uneskos: <http://purl.org/roh/unesco-individuals#>
prefix ro: <http://purl.org/roh_edma/mirror/obo/ro#> 

SELECT (COUNT(DISTINCT ?publication) as ?publicationCount) ?organization ?university
WHERE {
  ?publication         a bibo:Document ;
                       roh:hasKnowledgeArea uneskos:120304;
                       vivo:hasPublicationVenue        ?journal;
                       roh:correspondingOrganization ?organization.
  ?journal	a bibo:Journal . 
  ?organization a ?classOrganization.
  OPTIONAL{ ?organization
                ro:BFO_0000050+ ?university. 
    ?university a vivo:University.}
  
  Filter(?classOrganization = roh:ResearchGroup || ?classOrganization = roh:ResearchInstitute) 
 }

GROUP BY ?organization ?university