PREFIX vivo: <http://purl.org/roh_edma/mirror/vivo#>
PREFIX bibo:  <http://purl.org/roh_edma/mirror/bibo#>
PREFIX roh: <http://purl.org/roh_edma#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
SELECT  ?document ?documentType
WHERE {
?dossier a roh:Dossier .
?dossier vivo:relates <http://purl.org/roh_edma/data#a-project>, ?document .
?document a ?documentType .
?documentType rdfs:subClassOf bibo:Report .FILTER NOT EXISTS {
?document a ?otherClass .
?otherClass rdfs:subClassOf ?documentType .
FILTER (?otherClass != ?documentType)
}
} 

