PREFIX foaf: <http://purl.org/roh_edma/mirror/foaf#>
PREFIX roh: <http://purl.org/roh_edma#>
PREFIX vivo:  <http://purl.org/roh_edma/mirror/vivo#>
PREFIX unesco: <http://purl.org/roh/unesco-individuals#>
PREFIX ro: <http://purl.org/obo/owl/ro#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT distinct ?researcher ?center ?positionClass
WHERE {{
  ?researcher	roh:hasKnowledgeArea ?area;
  				roh:hasPosition ?position .
  ?position vivo:relates ?center ;
  			a	?positionClass.
	
	Filter(?positionClass != owl:NamedIndividual) # Esta clausula es necesaria debida a la forma de generar los datos
  ?center a roh:ResearchGroup .}
   UNION {
     ?researcher	roh:hasKnowledgeArea ?area;
  				roh:hasPosition ?position .
  ?position vivo:relates ?center ;
  			a	?positionClass.
Filter(?positionClass != owl:NamedIndividual) # Esta clausula es necesaria debida a la forma de generar los datos

  ?center a roh:ResearchInstitute .
  }

FILTER NOT EXISTS {
?position a ?otherClass.
?otherClass rdfs:subClassOf ?positionClass .
FILTER (?otherClass != ?positionClass) 

}
}