PREFIX foaf: <http://purl.org/roh_edma/mirror/foaf#>
PREFIX roh: <http://purl.org/roh_edma#>
PREFIX vivo:  <http://purl.org/roh_edma/mirror/vivo#>
PREFIX unesco: <http://purl.org/roh/unesco-individuals#>
PREFIX ro: <http://purl.org/obo/owl/ro#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?researcher ?center ?positionClass
WHERE {{
  ?researcher	roh:hasKnowledgeArea uneskos:120304;
  			vivo:relatedBy  ?position .
  ?position a roh:ResearcherPosition.
  ?position vivo:relates ?center ;
  			a	?positionClass.
}
   UNION {
     ?researcher	roh:hasKnowledgeArea  uneskos:120304;
  				roh:hasPosition ?position .
  ?position vivo:relates ?center ;
  			a	?positionClass.

  ?center a roh:ResearchInstitute .
  }

FILTER NOT EXISTS {
?position a ?otherClass.
?otherClass rdfs:subClassOf ?positionClass .
FILTER (?otherClass != ?positionClass) 

}
}


SELECT ?researcher ?center ?positionClass
WHERE {
  ?researcher	roh:hasKnowledgeArea ?area;
  			vivo:relatedBy  ?position .
  ?position vivo:relates ?center ;
            a	?positionClass.
    ?center a ?classCenter.
 FILTER(?classCenter = roh:ResearchGroup || ?classCenter = roh:ResearchInstitute) 