PREFIX roh: <http://purl.org/roh_edma#>
PREFIX ro: <http://purl.org/roh_edma/mirror/obo/ro#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix vivo: <http://purl.org/roh_edma/mirror/vivo#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#>
select (count( ?knowledgeArea) AS ?n_knowledgeArea)  ?knowledgeArea
where {{
 ?sujeto a vivo:Project;
    roh:hasKnowledgeArea ?knowledgeArea. }
  UNION{
      ?sujeto a roh:ResearchObject;
          roh:hasKnowledgeArea ?knowledgeArea
    }
} GRoup by ?knowledgeArea
ORDER by desc( ?n_knowledgeArea)




