PREFIX ro: <http://purl.org/roh/mirror/obo/ro#>
PREFIX bibo:  <http://purl.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bfo: <http://purl.org/roh/mirror/obo/bfo#>
SELECT ?researcher ?conference ?roleClass 
WHERE {
	?conference	a	bibo:Conference .
	?role 		bfo:BFO_0000054 ?conference .
	?role 		a ?roleClass ;
      			ro:RO_0000052 ?researcher .
  FILTER NOT EXISTS {
	?role 		a ?otherClass .
	?otherClass rdfs:subClassOf ?roleClass .
	FILTER (?otherClass != ?roleClass)
  }
}