PREFIX roh: <http://purl.org/roh_edma#>
PREFIX vivo: <http://purl.org/roh_edma/mirror/vivo#>
PREFIX foaf: <http://purl.org/roh_edma/mirror/foaf#>
prefix ro: <http://purl.org/roh_edma/mirror/obo/ro#>
SELECT DISTINCT ?project ?organization ?otherOrganization 
WHERE {
?project a vivo:Project ;
		vivo:relates ?role ;
		vivo:relates ?otherRole .
?role ro:RO_0000052 ?organization .
?organization a foaf:Organization .
?otherRole ro:RO_0000052 ?otherOrganization .
?otherOrganization a foaf:Organization .
FILTER (?organization != ?otherOrganization) 
}