PREFIX roh: <http://purl.org/roh_edma#>
PREFIX vivo: <http://purl.org/roh_edma/mirror/vivo#>
PREFIX ro: <http://purl.org/roh_edma/mirror/obo/ro#>
PREFIX foaf: <http://purl.org/roh_edma/mirror/foaf#>

SELECT ?organization ?knowledgeArea (SUM(?monetaryAmount) as ?totalFunding) 
WHERE {
?project a vivo:Project ;
        roh:hasKnowledgeArea ?knowledgeArea ;
        roh:isSupportedBy ?funding .
?funding ro:BFO_0000051 ?fundingAmount .
?fundingAmount roh:monetaryAmount ?monetaryAmount ;
r           oh:grants ?organization .
?organization a foaf:Organization .
} 
GROUP BY ?organization ?knowledgeArea