PREFIX roh: <http://purl.org/roh_edma#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?center (COUNT(?accreditation) AS ?numberOfSeals) 
WHERE {{
 ?center a roh:ResearchGroup ;
         roh:hasAccreditation ?accreditation .
 }UNION{
 ?center a roh:ResearchInstitute ;
         roh:hasAccreditation ?accreditation .
 
}}GROUP BY ?center
ORDER BY DESC(?numberOfSeals)
LIMIT 10