PREFIX roh: <http://purl.org/roh_edma#>
PREFIX vivo: <http://purl.org/roh_edma/mirror/vivo#>
PREFIX foaf: <http://purl.org/roh_edma/mirror/foaf#>
SELECT ?researcher ?grant 
WHERE {
?contract a roh:PersonContract ; 
vivo:relates ?researcher .
?researcher a foaf:Person .
{
SELECT ?grant 
WHERE {
?grant a roh:Grant .
?contract vivo:relates ?grant .
}
}
}