PREFIX roh: <http://purl.org/roh#>
PREFIX vivo: <http://purl.org/roh/mirror/vivo#>
PREFIX bibo:  <http://purl.org/roh/mirror/bibo#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>
PREFIX ro: <http://purl.org/roh/mirror/obo/ro#>
SELECT DISTINCT ?university ?phdThesis 
WHERE {
?phdThesis a roh:PhDThesis 
;bibo:authorList ?authorList ;
dc:title ?title .
?authorList rdfs:member ?author .
?author roh:hasPosition ?position .
?position vivo:relates ?researchGroup .
?researchGroup a roh:ResearchGroup .
?university ro:BFO_0000051 ?researchGroup .
FILTER regex(?title, "fabulous", "i")}
