PREFIX roh: <http://purl.org/roh_edma#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

select   ?element
where {
    <http://purl.org/roh_edma/data#repository-1>
                roh:repositoryHasPart ?element.
    
}