PREFIX roh: <http://purl.org/roh_edma#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

select   ?researchResult ?resource 
where {
    ?researchResult a roh:ResearchResult;
                    roh:correspondingAuthor <http://purl.org/roh_edma/data#investigador-1> ;
                    roh:researchResultHasPart ?resource.
    
}
