PREFIX ro: <http://purl.org/obo/owl/ro#>
prefix vivo: <http://purl.org/roh_edma/mirror/vivo#> 
prefix roh: <http://purl.org/roh_edma#>
prefix bibo: <http://purl.org/roh_edma/mirror/bibo#> 
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://purl.org/roh_edma/mirror/foaf#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix uneskos:  <http://purl.org/roh/unesco-individuals#>
prefix gn: <http://purl.org/roh_edma/mirror/geonames#>

SELECT
(COUNT(DISTINCT ?RO) as ?CountResearchObject) ?comunidadAutonoma
WHERE {
  ?RO         a roh:ResearchObject;
              roh:correspondingOrganization ?organization.
?organization	gn:locatedIn        ?location ;
              a ?classOrganization.
Filter(?classOrganization = roh:ResearchInstitute || ?classOrganization = roh:ResearchGroup)
 SERVICE ?location {
  	?location <http://www.geonames.org/ontology#parentADM1> ?comunidadAutonoma .
  }
}
GROUP BY ?comunidadAutonoma
