# En esta consulta hay que comprobar que funciona la parte de consultar a Geonames, ya que en Fuseki no funcionan las querys federadas

prefix vivo: <http://purl.org/roh_edma/mirror/vivo#>
prefix roh: <http://purl.org/roh_edma#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix foaf: <http://purl.org/roh_edma/mirror/foaf#>
prefix unesco: <http://purl.org/roh/unesco-individuals#>
prefix ro: <http://purl.org/roh_edma/mirror/obo/ro#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ero: <http://purl.org/roh_edma/mirror/obo/ero#>
prefix gn: <http://purl.org/roh_edma/mirror/geonames#>
prefix iao: <http://purl.org/roh_edma/mirror/obo/iao#>
prefix dc: <http://purl.org/dc/elements/1.1/>
SELECT
(COUNT(DISTINCT ?organizacion) as ?n_organizacion) ?knowledgeArea ?comunidadAutonoma
WHERE {

  ?organizacion	a               vivo:University;
                gn:locatedIn     ?location ;
                roh:hasKnowledgeArea ?knowledgeArea.
 SERVICE ?location {
  	?location <http://www.geonames.org/ontology#parentADM1> ?comunidadAutonoma .
 }
}
GROUP BY ?knowledgeArea ?comunidadAutonoma 