PREFIX asioModules:  <http://purl.org/hercules/asio/modules#>
PREFIX foaf:    <https://xmlns.com/foaf/0.1/>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX vivo:    <http://purl.org/roh/mirror/vivo>

CONSTRUCT {
    ?x a vivo:University .
} WHERE {
    ?x a skos:Concept .
    ?x skos:inScheme asioModules:UniversityList .
}

