# This is a basic workflow to help you get started with Actions

name: Validation questions in add_some branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: [ 'add_some' ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true 

    - name: Checkout pellet
      uses: actions/checkout@v2
      with: 
        repository: stardog-union/pellet
        path: pellet

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Pellet reasoner
      working-directory: pellet
      run: mvn install

    - name: Launch tests
      working-directory: /home/runner/work/ROH/ROH/validation-questions
      run: mvn surefire-report:report  -Dmodel=/home/runner/work/ROH/ROH/modules/core/roh-core.ttl,/home/runner/work/ROH/ROH/validation-data/rdf/roh_data_edma.ttl,https://raw.githubusercontent.com/HerculesCRUE/ROH/add_some/roh/modules/knowledge-area/unesco-knowledge-area.rdf  -DqueryFolder=/home/runner/work/ROH/ROH/validation-questions/sparql-query/


   