# This is a basic workflow to help you get started with Actions

name: widoco

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches: [ 'edma' ]
  pull_request:
    branches: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2
  #    with:
  #      submodules: true
        ref: 'widoco-action'
      
    - name: Download widoco
      run: mkdir widoco && wget -O widoco/widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.14/widoco-1.4.14-jar-with-dependencies.jar
  
    - name: Compile documentation
      run: |
        cd widoco
        java -jar ./widoco.jar \
        -ontFile ../sigmaaie/modules/core/roh-core.ttl \
        -oops \
        -webVowl \
        -includeAnnotationProperties \
        -outFolder output/roh \
        -rewriteAll \
        -confFile config-roh \
        -includeImportedOntologies \
        -uniteSections \
        -excludeIntroduction

    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        keep_history: true 
        build_dir: widoco/output 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}